eng_dict = {
    "main_window_title": "Task Manager",
    "task_name_label": "Task name",
    "task_cat_label": "Category",
    "task_desc_label": "Description",
    "task_deadline_label": "Deadline",
    "task_exec_date_label": "Execution planned on",
    "subtasks_label": "Subtasks",
    "daily_title_label": "DAILY LIST",
    "action_menu_button": "ACTION MENU",
    "all_tasks_button": "ALL TASKS",
    "new_subtask_button": "Add subtask",
    "delete_subtask_button": "Delete subtask",
    "delete_task_button": "Delete task",
    "all_tasks_window_title": "All tasks",
    "back_button": "BACK",
    "checked_tasks_button": "Checked tasks",
    "checked_tasks_window_title": "Checked tasks by date",
    "template_button": "Use as template",
    "choose_date_button": "Choose",
    "date_label": "Choose the day on which the task was executed:",
    "add_tasks_window_title": "Add task",
    "top_title_add_window": "ADD TASK",
    "none_button": "none",
    "action_menu_window_title": "Action menu",
    "action_menu_title": "ACTION MENU",
    "del_all_tasks_label": "Delete all checked off tasks",
    "cat_label": "Manage categories",
    "real_cat_label": "A cat",
    "add_category_button": "Add category",
    "delete_category_button": "Delete category",
    "category_window_title": "MANAGE CATEGORIES",
    "settings_window_title": "Settings",
    "english": "english",
    "polish": "polish",
    "silly": "silly",
    "high": "high",
    "medium": "medium",
    "low": "low",
    "settings_title": "SETTINGS",
    "choose_language_option_label": "Choose language option:",
    "choose_pr_lvl_time_windows_label": "Choose time windows (in days) for each priority level:",
    "high_lvl_label": "high level:",
    "med_lvl_label": "medium level:",
    "low_lvl_label": "low level:",
    "choose_pr_lvl_daily_label": "Choose priority level to display on daily:",
    "save_button": "Save"
}

pol_dict = {
    "main_window_title": "Aplikacja do zarządzania zadaniami",
    "task_name_label": "Tytuł zadania",
    "task_cat_label": "Kategoria",
    "task_desc_label": "Opis",
    "task_deadline_label": "Termin ostateczny",
    "task_exec_date_label": "Wykonanie planowane na",
    "subtasks_label": "Podzadania",
    "daily_title_label": "NA DZIŚ",
    "action_menu_button": "MENU AKCJI",
    "all_tasks_button": "WSZYSTKIE ZADANIA",
    "new_subtask_button": "Dodaj podzadanie",
    "delete_subtask_button": "Usuń podzadanie",
    "delete_task_button": "Usuń zadanie",
    "all_tasks_window_title": "Wszystkie zadania",
    "back_button": "POWRÓT",
    "checked_tasks_button": "Wykonane zadania",
    "checked_tasks_window_title": "Wykonane zadania z podziałem na dni",
    "template_button": "Wykorzystaj jako szablon",
    "choose_date_button": "Wybierz",
    "date_label": "Wybierz dzień, w którym zadanie zostało wykonane:",
    "add_tasks_window_title": "Dodaj zadanie",
    "top_title_add_window": "DODAJ ZADANIE",
    "none_button": "brak",
    "action_menu_window_title": "Menu akcji",
    "action_menu_title": "MENU AKCJI",
    "del_all_tasks_label": "Usuń wszystkie wykonane zadania",
    "cat_label": "Zarządzaj kategoriami",
    "real_cat_label": "Kot",
    "add_category_button": "Dodaj kategorię",
    "delete_category_button": "Usuń kategorię",
    "category_window_title": "ZARZĄDZAJ KATEGORIAMI",
    "settings_window_title": "Ustawienia",
    "english": "angielski",
    "polish": "polski",
    "silly": "beka",
    "high": "wysoki",
    "medium": "średni",
    "low": "niski",
    "settings_title": "USTAWIENIA",
    "choose_language_option_label": "Wybierz wersję językową:",
    "choose_pr_lvl_time_windows_label": "Wybiesz przedziały czasowe (w dniach) dla każdego poziomu priorytetu:",
    "high_lvl_label": "wysoki poziom:",
    "med_lvl_label": "średni poziom:",
    "low_lvl_label": "niski poziom:",
    "choose_pr_lvl_daily_label": "Wybierz poziom priorytetu do uwzględnienia w liście \"na dziś\":",
    "save_button": "Zapisz"
}

silly_dict = {
    "main_window_title": "Apka do zbierania taskow do kupy",
    "task_name_label": "Quest",
    "task_cat_label": "Kategoria",
    "task_desc_label": "A właściwie to co?",
    "task_deadline_label": "Do wtedy masz zrobić",
    "task_exec_date_label": "A planowane (ta, jasne) na wtedy",
    "subtasks_label": "Side-questy",
    "daily_title_label": "OTO DAILY BYCZKU",
    "action_menu_button": "FUNKY ACTIONS",
    "all_tasks_button": "TO NIE WSZYSTKO",
    "new_subtask_button": "Kolejny (ugh) sidequest",
    "delete_subtask_button": "Abort sidequest",
    "delete_task_button": "Abort me mother",
    "all_tasks_window_title": "Reszta questów",
    "back_button": "WRACAJTA",
    "checked_tasks_button": "Spełnione questy",
    "checked_tasks_window_title": "Spełnione questy",
    "template_button": "Wykorzystaj jako szablon TY LENIU",
    "choose_date_button": "DAWAAAAAJ",
    "date_label": "Wybierz dzień, w którym quest został odwalony:",
    "add_tasks_window_title": "Dodaj questa",
    "top_title_add_window": "DODAJ QUESTA",
    "none_button": "po co to komu",
    "action_menu_window_title": "Funky akcje",
    "action_menu_title": "FUNKY AKCJE",
    "del_all_tasks_label": "Abort wszystkie odwalone sidequesty",
    "cat_label": "Weź ogarnij te kategorie",
    "real_cat_label": "*inhales* KOT",
    "add_category_button": "Dawaj nową",
    "delete_category_button": "Wywal tą",
    "category_window_title": "OGARNIJ TE KATEGORIE",
    "settings_window_title": "Wajchy, pokrętła i inne",
    "english": "brytole",
    "polish": "polaczki",
    "silly": "BEKA",
    "high": "oj ciężko byczku",
    "medium": "lepiej",
    "low": "aaah, chill",
    "settings_title": "USTAWIENIA",
    "choose_language_option_label": "Wybierz język:",
    "choose_pr_lvl_time_windows_label": "Wybiesz (w dniach) jak bardzo masz panikować:",
    "high_lvl_label": "poziom \"oj ciężko byczku\":",
    "med_lvl_label": "poziom \"lepiej\":",
    "low_lvl_label": "poziom \"aaah, chill\":",
    "choose_pr_lvl_daily_label": "Wybierz poziom priorytetu na daily:",
    "save_button": "Zapisz"
}

language_options = {
    "english": eng_dict,
    "polish": pol_dict,
    "silly": silly_dict
}